// Shared symbol and template data for panel and modal

export const symbolGroups = [
  ['Common', [
    ['a/b', '\\frac{a}{b}'],
    ['\u221Ax', '\\sqrt{x}'],
    ['x\u207F', 'x^{n}'],
    ['x\u1D62', 'x_{i}'],
    ['\u00B1', '\\pm'],
    ['\u221E', '\\infty'],
    ['\u2260', '\\neq'],
    ['\u2264', '\\leq'],
    ['\u2265', '\\geq'],
    ['\u2248', '\\approx'],
  ]],
  ['Calculus', [
    ['\u222B', '\\int_{a}^{b}'],
    ['\u222C', '\\iint'],
    ['\u03A3', '\\sum_{i=1}^{n}'],
    ['\u03A0', '\\prod_{i=1}^{n}'],
    ['lim', '\\lim_{x \\to \\infty}'],
    ['\u2202', '\\frac{\\partial}{\\partial x}'],
    ['\u2207', '\\nabla'],
    ['d/dx', '\\frac{d}{dx}'],
    ['\u222B\u222B\u222B', '\\iiint'],
    ['\u222E', '\\oint'],
  ]],
  ['Trig & Log', [
    ['sin', '\\sin'],
    ['cos', '\\cos'],
    ['tan', '\\tan'],
    ['ln', '\\ln'],
    ['log', '\\log'],
    ['sin\u207B\u00B9', '\\arcsin'],
    ['cos\u207B\u00B9', '\\arccos'],
    ['tan\u207B\u00B9', '\\arctan'],
    ['e\u02E3', 'e^{x}'],
    ['|\u2009|', '\\left| x \\right|'],
  ]],
  ['Greek', [
    ['\u03B1', '\\alpha'],
    ['\u03B2', '\\beta'],
    ['\u03B3', '\\gamma'],
    ['\u03B4', '\\delta'],
    ['\u03B5', '\\epsilon'],
    ['\u03B8', '\\theta'],
    ['\u03BB', '\\lambda'],
    ['\u03BC', '\\mu'],
    ['\u03C0', '\\pi'],
    ['\u03C3', '\\sigma'],
    ['\u03C6', '\\phi'],
    ['\u03C9', '\\omega'],
    ['\u0393', '\\Gamma'],
    ['\u0394', '\\Delta'],
    ['\u03A9', '\\Omega'],
  ]],
  ['Sets & Logic', [
    ['\u2208', '\\in'],
    ['\u2209', '\\notin'],
    ['\u2286', '\\subseteq'],
    ['\u222A', '\\cup'],
    ['\u2229', '\\cap'],
    ['\u2205', '\\emptyset'],
    ['\u2200', '\\forall'],
    ['\u2203', '\\exists'],
    ['\u21D2', '\\Rightarrow'],
    ['\u21D4', '\\Leftrightarrow'],
    ['\u2234', '\\therefore'],
    ['\u2235', '\\because'],
    ['\u2115', '\\mathbb{N}'],
    ['\u211D', '\\mathbb{R}'],
    ['\u2124', '\\mathbb{Z}'],
  ]],
  ['Arrows & Dots', [
    ['\u2192', '\\to'],
    ['\u2190', '\\leftarrow'],
    ['\u2194', '\\leftrightarrow'],
    ['\u21A6', '\\mapsto'],
    ['\u22EF', '\\cdots'],
    ['\u22EE', '\\vdots'],
    ['\u22F1', '\\ddots'],
  ]],
  ['Accents', [
    ['\u0302x', '\\hat{x}'],
    ['\u0304x', '\\bar{x}'],
    ['\u0307x', '\\dot{x}'],
    ['\u20D7x', '\\vec{x}'],
    ['x\u0303', '\\tilde{x}'],
  ]],
  ['Formatting', [
    ['\u21B5', ' \\\\ '],
    ['text', '\\text{}'],
    ['bold', '\\mathbf{}'],
    ['italic', '\\mathit{}'],
    ['underline', '\\underline{}'],
    ['cancel', '\\cancel{}'],
    ['box', '\\boxed{}'],
    ['color', '\\color{red}{}'],
  ]],
  ['Spacing & Brackets', [
    ['\\,', '\\,'],
    ['\\;', '\\;'],
    ['quad', '\\quad'],
    ['( )', '\\left( \\right)'],
    ['[ ]', '\\left[ \\right]'],
    ['{ }', '\\left\\{ \\right\\}'],
    ['| |', '\\left| \\right|'],
  ]],
];

export const templateGroups = [
  ['Algebra', [
    ['Quadratic', 'ax^2 + bx + c = 0'],
    ['Quadratic formula', 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}'],
    ['Binomial expansion', '(a+b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k} b^k'],
    ['System of equations', '\\begin{cases} 2x + 3y = 7 \\\\ x - y = 1 \\end{cases}'],
    ['Absolute value', '|x| = \\begin{cases} x & \\text{if } x \\geq 0 \\\\ -x & \\text{if } x < 0 \\end{cases}'],
  ]],
  ['Calculus', [
    ['Derivative', '\\frac{d}{dx}\\left[ f(x) \\right]'],
    ['Definite integral', '\\int_{a}^{b} f(x)\\, dx'],
    ['Limit', '\\lim_{x \\to a} f(x) = L'],
    ['Chain rule', '\\frac{d}{dx}[f(g(x))] = f\'(g(x)) \\cdot g\'(x)'],
    ['Taylor series', 'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n'],
    ['Power series', '\\sum_{n=0}^{\\infty} a_n x^n'],
    ['Partial derivative', '\\frac{\\partial^2 f}{\\partial x \\partial y}'],
  ]],
  ['Linear Algebra', [
    ['2\u00D72 Matrix', '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}'],
    ['3\u00D73 Matrix', '\\begin{pmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{pmatrix}'],
    ['Determinant', '\\det(A) = \\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix} = ad - bc'],
    ['Augmented matrix', '\\left(\\begin{array}{cc|c} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\end{array}\\right)'],
    ['Dot product', '\\vec{a} \\cdot \\vec{b} = \\sum_{i=1}^{n} a_i b_i'],
  ]],
  ['Probability & Stats', [
    ["Bayes' theorem", 'P(A|B) = \\frac{P(B|A)\\,P(A)}{P(B)}'],
    ['Binomial coeff.', '\\binom{n}{r} = \\frac{n!}{r!(n-r)!}'],
    ['Mean', '\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n} x_i'],
    ['Variance', '\\sigma^2 = \\frac{1}{n}\\sum_{i=1}^{n}(x_i - \\mu)^2'],
    ['Normal dist.', 'f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}}\\,e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}'],
    ['Expected value', 'E[X] = \\sum_{i} x_i \\, P(X = x_i)'],
    ['Combination', 'C(n,r) = \\frac{n!}{r!(n-r)!}'],
  ]],
  ['Trig & Geometry', [
    ['Pythagorean', 'a^2 + b^2 = c^2'],
    ['Trig identity', '\\sin^2\\theta + \\cos^2\\theta = 1'],
    ['Euler\u2019s formula', 'e^{i\\theta} = \\cos\\theta + i\\sin\\theta'],
    ['Law of cosines', 'c^2 = a^2 + b^2 - 2ab\\cos C'],
    ['Area of triangle', 'A = \\frac{1}{2}ab\\sin C'],
  ]],
  ['Tables', [
    ['Simple table', '\\begin{array}{c|c|c} x & y & z \\\\ \\hline 1 & 2 & 3 \\\\ 4 & 5 & 6 \\end{array}'],
    ['Left-aligned table', '\\begin{array}{l|r|r} \\text{Item} & \\text{Qty} & \\text{Price} \\\\ \\hline \\text{Apples} & 3 & 1.50 \\\\ \\text{Bananas} & 5 & 2.00 \\\\ \\hline & \\text{Total} & 3.50 \\end{array}'],
    ['Truth table', '\\begin{array}{c|c|c|c} p & q & p \\land q & p \\lor q \\\\ \\hline T & T & T & T \\\\ T & F & F & T \\\\ F & T & F & T \\\\ F & F & F & F \\end{array}'],
    ['Bordered table', '\\begin{array}{|c|c|c|} \\hline x & f(x) & f\'(x) \\\\ \\hline 0 & 1 & 0 \\\\ 1 & 2 & 3 \\\\ 2 & 5 & 8 \\\\ \\hline \\end{array}'],
    ['Frequency table', '\\begin{array}{|c|c|c|} \\hline \\text{Class} & f & cf \\\\ \\hline 0\\text{-}10 & 5 & 5 \\\\ 10\\text{-}20 & 8 & 13 \\\\ 20\\text{-}30 & 12 & 25 \\\\ \\hline \\end{array}'],
  ]],
  ['Structures', [
    ['Piecewise', '\\begin{cases} f(x) & \\text{if } x > 0 \\\\ g(x) & \\text{if } x \\leq 0 \\end{cases}'],
    ['Aligned equations', '\\begin{aligned} f(x) &= x^2 + 2x + 1 \\\\ &= (x+1)^2 \\end{aligned}'],
    ['Numbered steps', '\\begin{aligned} &(1) \\quad 2x + 3 = 7 \\\\ &(2) \\quad 2x = 4 \\\\ &(3) \\quad x = 2 \\end{aligned}'],
    ['Fraction stack', '\\cfrac{1}{1+\\cfrac{1}{1+\\cfrac{1}{x}}}'],
    ['Floor / Ceiling', '\\lfloor x \\rfloor \\quad \\lceil x \\rceil'],
    ['Norm', '\\left\\| \\vec{v} \\right\\|'],
    ['Horizontal rule', '\\text{Before} \\\\[4pt] \\rule{8cm}{0.4pt} \\\\[4pt] \\text{After}'],
    ['Boxed result', '\\boxed{x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}}'],
    ['Underbrace', '\\underbrace{a + a + \\cdots + a}_{n \\text{ times}} = na'],
    ['Overbrace', '\\overbrace{1 + 2 + \\cdots + n}^{\\frac{n(n+1)}{2}}'],
  ]],
];
