// Formula library — IB Data Booklet formulae organised by subject and topic

export const formulaLibrary = [
  {
    subject: 'IB Physics',
    categories: [
      {
        name: '1. Measurements & Uncertainties',
        formulae: [
          ['Fractional uncertainty (×÷)', '\\frac{\\Delta z}{z} = \\frac{\\Delta x}{x} + \\frac{\\Delta y}{y}'],
          ['Absolute uncertainty (±)', '\\Delta z = \\Delta x + \\Delta y'],
          ['Uncertainty in a power', '\\frac{\\Delta z}{z} = n \\frac{\\Delta x}{x}'],
          ['Percentage uncertainty', '\\text{\\% unc} = \\frac{\\Delta x}{x} \\times 100'],
        ],
      },
      {
        name: '2. Mechanics',
        formulae: [
          ['Displacement', 's = ut + \\tfrac{1}{2}at^2'],
          ['Velocity-time', 'v = u + at'],
          ['Velocity-displacement', 'v^2 = u^2 + 2as'],
          ['Average velocity', 's = \\frac{(v+u)}{2}t'],
          ['Weight', 'F_W = mg'],
          ['Friction', 'F_f = \\mu F_N'],
          ['Momentum', 'p = mv'],
          ['Impulse', 'J = F\\Delta t = \\Delta p'],
          ["Newton's 2nd law", 'F = ma'],
          ["Newton's 2nd (momentum)", 'F = \\frac{\\Delta p}{\\Delta t}'],
          ['Kinetic energy', 'E_k = \\tfrac{1}{2}mv^2'],
          ['Gravitational PE', '\\Delta E_p = mg\\Delta h'],
          ['Elastic PE', 'E_{el} = \\tfrac{1}{2}k\\Delta x^2'],
          ["Hooke's law", 'F = k\\Delta x'],
          ['Work done', 'W = Fs\\cos\\theta'],
          ['Power', 'P = \\frac{W}{t} = Fv'],
          ['Efficiency', '\\eta = \\frac{E_{\\text{useful}}}{E_{\\text{input}}}'],
          ['Torque', '\\tau = Fr\\sin\\theta'],
          ['Moment of couple', '\\tau = Fd'],
        ],
      },
      {
        name: '3. Thermal Physics',
        formulae: [
          ['Pressure', 'P = \\frac{F}{A}'],
          ['Density', '\\rho = \\frac{m}{V}'],
          ['Specific heat capacity', 'Q = mc\\Delta T'],
          ['Specific latent heat', 'Q = mL'],
          ['Ideal gas law', 'pV = nRT'],
          ['Ideal gas (molecular)', 'pV = NkT'],
          ['Avg KE per molecule', '\\bar{E}_k = \\tfrac{3}{2}kT'],
          ['Kinetic theory pressure', 'p = \\frac{1}{3}\\frac{Nm}{V}\\overline{v^2}'],
          ['Moles', 'n = \\frac{N}{N_A}'],
          ['Boltzmann constant', 'k = \\frac{R}{N_A}'],
        ],
      },
      {
        name: '4. Waves',
        formulae: [
          ['Wave speed', 'v = f\\lambda'],
          ['Period-frequency', 'f = \\frac{1}{T}'],
          ['Intensity', 'I = \\frac{P}{A}'],
          ['Intensity ∝ amplitude²', 'I \\propto A^2'],
          ['Intensity (point source)', 'I = \\frac{P}{4\\pi r^2}'],
          ["Snell's law", 'n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2'],
          ['Refractive index', 'n = \\frac{c}{v}'],
          ['Critical angle', '\\sin\\theta_c = \\frac{n_2}{n_1}'],
          ["Malus's law", 'I = I_0 \\cos^2\\theta'],
          ["Brewster's angle", '\\tan\\theta_B = \\frac{n_2}{n_1}'],
          ['Harmonics (both ends)', '\\lambda_n = \\frac{2L}{n}'],
          ['Harmonics (one end closed)', '\\lambda_n = \\frac{4L}{n}, \\quad n = 1,3,5,\\ldots'],
          ['Thin lens equation', '\\frac{1}{f} = \\frac{1}{v} + \\frac{1}{u}'],
          ['Magnification (lens)', 'm = \\frac{v}{u}'],
          ['Power of a lens', 'P = \\frac{1}{f}'],
        ],
      },
      {
        name: '5. Electricity & Magnetism',
        formulae: [
          ['Electric current', 'I = \\frac{\\Delta q}{\\Delta t}'],
          ["Coulomb's law", 'F = k\\frac{q_1 q_2}{r^2}'],
          ['Electric field (definition)', 'E = \\frac{F}{q}'],
          ['Electric field (point charge)', 'E = k\\frac{q}{r^2}'],
          ['Electric field (parallel plates)', 'E = \\frac{V}{d}'],
          ['Electric PE', 'E_p = k\\frac{q_1 q_2}{r}'],
          ['Electric potential', 'V = k\\frac{q}{r}'],
          ['Potential difference', 'V = \\frac{W}{q}'],
          ["Ohm's law", 'V = IR'],
          ['Resistance', 'R = \\frac{\\rho L}{A}'],
          ['Power (electrical)', 'P = IV = I^2R = \\frac{V^2}{R}'],
          ['Resistors in series', 'R_T = R_1 + R_2 + \\cdots'],
          ['Resistors in parallel', '\\frac{1}{R_T} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\cdots'],
          ['EMF and internal resistance', '\\varepsilon = I(R + r)'],
          ['Force on moving charge', 'F = qvB\\sin\\theta'],
          ['Force on current-carrying wire', 'F = BIL\\sin\\theta'],
          ['Magnetic flux', '\\Phi = BA\\cos\\theta'],
          ['Capacitors in parallel', 'C_T = C_1 + C_2 + \\cdots'],
          ['Capacitors in series', '\\frac{1}{C_T} = \\frac{1}{C_1} + \\frac{1}{C_2} + \\cdots'],
        ],
      },
      {
        name: '6. Circular Motion & Gravitation',
        formulae: [
          ['Period of circular motion', 'T = \\frac{2\\pi r}{v}'],
          ['Angular velocity', '\\omega = \\frac{2\\pi}{T} = 2\\pi f'],
          ['Centripetal acceleration', 'a = \\frac{v^2}{r} = \\omega^2 r'],
          ['Centripetal force', 'F = \\frac{mv^2}{r} = m\\omega^2 r'],
          ['Linear-angular speed', 'v = \\omega r'],
          ["Newton's law of gravitation", 'F = G\\frac{m_1 m_2}{r^2}'],
          ['Gravitational field strength', 'g = G\\frac{M}{r^2}'],
          ['Orbital speed', 'v = \\sqrt{\\frac{GM}{r}}'],
          ["Kepler's third law", 'T^2 = \\frac{4\\pi^2}{GM}r^3'],
        ],
      },
      {
        name: '7. Atomic, Nuclear & Particle',
        formulae: [
          ['Photon energy', 'E = hf = \\frac{hc}{\\lambda}'],
          ['Mass-energy equivalence', 'E = mc^2'],
          ['Mass defect', '\\Delta m = Zm_p + Nm_n - m_{\\text{nucleus}}'],
          ['Binding energy', 'E_b = \\Delta m \\cdot c^2'],
          ['Radioactive decay', 'N = N_0 e^{-\\lambda t}'],
          ['Activity', 'A = \\lambda N = A_0 e^{-\\lambda t}'],
          ['Half-life', 't_{1/2} = \\frac{\\ln 2}{\\lambda}'],
          ['de Broglie wavelength', '\\lambda = \\frac{h}{p}'],
        ],
      },
      {
        name: '8. Energy Production',
        formulae: [
          ['Stefan-Boltzmann law', 'P = e\\sigma AT^4'],
          ["Wien's displacement law", '\\lambda_{\\max}T = 2.90 \\times 10^{-3}\\,\\text{m K}'],
          ['Luminosity', 'L = 4\\pi R^2 \\sigma T^4'],
          ['Apparent brightness', 'b = \\frac{L}{4\\pi d^2}'],
          ['Albedo', '\\alpha = \\frac{P_{\\text{scattered}}}{P_{\\text{incident}}}'],
          ['Emissivity power', 'P = e\\sigma A(T^4 - T_c^4)'],
        ],
      },
      {
        name: '9. Wave Phenomena (HL)',
        formulae: [
          ['Single-slit first minimum', '\\theta = \\frac{\\lambda}{b}'],
          ['Double-slit fringe spacing', 's = \\frac{\\lambda D}{d}'],
          ['Diffraction grating', 'd\\sin\\theta = n\\lambda'],
          ['Rayleigh criterion', '\\theta = 1.22\\frac{\\lambda}{b}'],
          ['Doppler effect (source)', "f' = f\\frac{v}{v \\pm u_s}"],
          ['Beat frequency', 'f_{\\text{beat}} = |f_1 - f_2|'],
          ['Doppler (observer)', "f' = f\\frac{v \\pm u_o}{v}"],
          ['Thin film interference', '2nt = (m + \\tfrac{1}{2})\\lambda'],
        ],
      },
      {
        name: '10. Fields (HL)',
        formulae: [
          ['Gravitational potential', 'V_g = -\\frac{GM}{r}'],
          ['Gravitational PE', 'E_p = -\\frac{GMm}{r}'],
          ['Escape speed', 'v_{\\text{esc}} = \\sqrt{\\frac{2GM}{r}}'],
          ['Orbital energy', 'E = -\\frac{GMm}{2r}'],
          ['Electric potential (point)', 'V_e = \\frac{kq}{r}'],
          ['Electric PE', 'E_p = \\frac{kq_1 q_2}{r}'],
          ['Field-potential relation (E)', 'E = -\\frac{\\Delta V}{\\Delta r}'],
          ['Field-potential relation (g)', 'g = -\\frac{\\Delta V_g}{\\Delta r}'],
        ],
      },
      {
        name: '11. EM Induction (HL)',
        formulae: [
          ["Faraday's law", '\\varepsilon = -N\\frac{\\Delta\\Phi}{\\Delta t}'],
          ['EMF (moving rod)', '\\varepsilon = BvL'],
          ['Peak EMF (AC)', '\\varepsilon_0 = NBA\\omega'],
          ['RMS voltage', 'V_{\\text{rms}} = \\frac{V_0}{\\sqrt{2}}'],
          ['RMS current', 'I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}}'],
          ['Transformer ratio', '\\frac{V_s}{V_p} = \\frac{N_s}{N_p}'],
          ['Capacitance', 'C = \\frac{q}{V}'],
          ['Capacitor energy', 'E = \\tfrac{1}{2}CV^2'],
          ['Capacitor discharge', 'q = q_0 e^{-t/RC}'],
          ['Time constant', '\\tau = RC'],
          ['Impedance (RLC)', 'Z = \\sqrt{R^2 + (X_L - X_C)^2}'],
          ['Resonant frequency', 'f_0 = \\frac{1}{2\\pi\\sqrt{LC}}'],
          ['AC voltage', 'V = V_0\\sin\\omega t'],
          ['Average power (AC)', 'P_{\\text{avg}} = V_{\\text{rms}}I_{\\text{rms}}'],
          ['Capacitive reactance', 'X_C = \\frac{1}{2\\pi fC}'],
          ['Inductive reactance', 'X_L = 2\\pi fL'],
          ['Inductor energy', 'E = \\tfrac{1}{2}LI^2'],
        ],
      },
      {
        name: '12. Quantum & Nuclear (HL)',
        formulae: [
          ['Photoelectric effect', 'E_k^{\\max} = hf - \\phi'],
          ['Stopping voltage', 'eV_s = hf - \\phi'],
          ['Heisenberg (Δx·Δp)', '\\Delta x \\Delta p \\geq \\frac{h}{4\\pi}'],
          ['Heisenberg (ΔE·Δt)', '\\Delta E \\Delta t \\geq \\frac{h}{4\\pi}'],
          ['Bohr energy levels', 'E_n = -\\frac{13.6}{n^2}\\,\\text{eV}'],
          ['Nuclear radius', 'R = R_0 A^{1/3}'],
          ['Absorbed dose', 'D = \\frac{E}{m}'],
          ['Dose equivalent', 'H = DQ'],
          ['Attenuation', 'I = I_0 e^{-\\mu x}'],
          ['Schrödinger probability', 'P = |\\Psi|^2 \\Delta V'],
          ['Tunnelling probability', 'T \\approx e^{-2\\kappa d}'],
          ['Half-value thickness', 'x_{1/2} = \\frac{\\ln 2}{\\mu}'],
        ],
      },
      {
        name: 'Constants',
        formulae: [
          ['Speed of light', 'c = 3.00 \\times 10^8\\,\\text{m s}^{-1}'],
          ['Planck constant', 'h = 6.63 \\times 10^{-34}\\,\\text{J s}'],
          ['Boltzmann constant', 'k = 1.38 \\times 10^{-23}\\,\\text{J K}^{-1}'],
          ['Stefan-Boltzmann', '\\sigma = 5.67 \\times 10^{-8}\\,\\text{W m}^{-2}\\text{K}^{-4}'],
          ['Gravitational constant', 'G = 6.67 \\times 10^{-11}\\,\\text{N m}^2\\text{kg}^{-2}'],
          ['Coulomb constant', 'k = 8.99 \\times 10^9\\,\\text{N m}^2\\text{C}^{-2}'],
          ['Avogadro constant', 'N_A = 6.02 \\times 10^{23}\\,\\text{mol}^{-1}'],
          ['Gas constant', 'R = 8.31\\,\\text{J mol}^{-1}\\text{K}^{-1}'],
          ['Electron charge', 'e = 1.60 \\times 10^{-19}\\,\\text{C}'],
          ['Electron mass', 'm_e = 9.11 \\times 10^{-31}\\,\\text{kg}'],
        ],
      },
    ],
  },
  {
    subject: 'IB Chemistry',
    categories: [
      {
        name: '1. Stoichiometry',
        formulae: [
          ['Moles (mass)', 'n = \\frac{m}{M}'],
          ['Moles (particles)', 'n = \\frac{N}{N_A}'],
          ['Moles (gas volume)', 'n = \\frac{V}{V_m}'],
          ['Concentration', 'c = \\frac{n}{V}'],
          ['Ideal gas law', 'PV = nRT'],
          ['Density', '\\rho = \\frac{m}{V}'],
          ['Percentage yield', '\\%\\text{ yield} = \\frac{\\text{actual}}{\\text{theoretical}} \\times 100'],
          ['Dilution', 'c_1 V_1 = c_2 V_2'],
        ],
      },
      {
        name: '2. Atomic Structure',
        formulae: [
          ['Photon energy', 'E = hf = \\frac{hc}{\\lambda}'],
          ['Wave equation', 'c = f\\lambda'],
          ['de Broglie wavelength', '\\lambda = \\frac{h}{mv}'],
          ['Energy level transition', '\\Delta E = hf'],
          ['H energy levels', 'E_n = -\\frac{13.6}{n^2}\\,\\text{eV}'],
        ],
      },
      {
        name: '5. Energetics',
        formulae: [
          ['Calorimetry', 'q = mc\\Delta T'],
          ['Enthalpy change', '\\Delta H = \\frac{q}{n}'],
          ["Hess's law (formation)", '\\Delta H^\\circ = \\sum\\Delta H^\\circ_f(\\text{prod}) - \\sum\\Delta H^\\circ_f(\\text{react})'],
          ["Hess's law (bonds)", '\\Delta H^\\circ = \\sum E(\\text{broken}) - \\sum E(\\text{formed})'],
          ['Gibbs free energy', '\\Delta G^\\circ = \\Delta H^\\circ - T\\Delta S^\\circ'],
          ['Gibbs and K', '\\Delta G^\\circ = -RT\\ln K'],
          ['Gibbs and cell potential', '\\Delta G^\\circ = -nFE^\\circ'],
          ['Entropy change', '\\Delta S^\\circ = \\sum S^\\circ(\\text{prod}) - \\sum S^\\circ(\\text{react})'],
          ['Enthalpy of solution', '\\Delta H^\\circ_{\\text{sol}} = -\\Delta H^\\circ_{\\text{latt}} + \\Delta H^\\circ_{\\text{hyd}}'],
          ['Born-Haber cycle', '\\Delta H^\\circ_{\\text{latt}} = \\Delta H^\\circ_f - \\Delta H^\\circ_{\\text{atom}} - \\Delta H^\\circ_{\\text{IE}} - \\Delta H^\\circ_{\\text{EA}}'],
        ],
      },
      {
        name: '6. Kinetics',
        formulae: [
          ['Rate of reaction', '\\text{rate} = -\\frac{\\Delta[\\text{reactant}]}{\\Delta t}'],
          ['Rate law', '\\text{rate} = k[A]^m[B]^n'],
          ['First order half-life', 't_{1/2} = \\frac{\\ln 2}{k}'],
          ['First order integrated', '\\ln[A] = \\ln[A]_0 - kt'],
          ['Arrhenius equation', 'k = Ae^{-E_a/RT}'],
          ['Arrhenius (log form)', '\\ln k = \\ln A - \\frac{E_a}{RT}'],
          ['Arrhenius (two-point)', '\\ln\\frac{k_1}{k_2} = \\frac{E_a}{R}\\left(\\frac{1}{T_2} - \\frac{1}{T_1}\\right)'],
          ['Second order integrated', '\\frac{1}{[A]} = \\frac{1}{[A]_0} + kt'],
          ['Zero order integrated', '[A] = [A]_0 - kt'],
        ],
      },
      {
        name: '7. Equilibrium',
        formulae: [
          ['Kc expression', 'K_c = \\frac{[C]^c[D]^d}{[A]^a[B]^b}'],
          ['Kp expression', 'K_p = \\frac{(p_C)^c(p_D)^d}{(p_A)^a(p_B)^b}'],
          ['Kp and Kc', 'K_p = K_c(RT)^{\\Delta n}'],
          ['Mole fraction', '\\chi_A = \\frac{n_A}{n_{\\text{total}}}'],
          ['Partial pressure', 'p_A = \\chi_A \\times P_{\\text{total}}'],
          ['Gibbs and Q', '\\Delta G = \\Delta G^\\circ + RT\\ln Q'],
          ['Reaction quotient', 'Q = \\frac{[C]^c[D]^d}{[A]^a[B]^b}'],
          ['Solubility product', 'K_{sp} = [M^{n+}]^p[X^{m-}]^q'],
        ],
      },
      {
        name: '8. Acids & Bases',
        formulae: [
          ['Kw', 'K_w = [\\ce{H+}][\\ce{OH-}] = 1.00 \\times 10^{-14}'],
          ['pH', '\\text{pH} = -\\log[\\ce{H+}]'],
          ['[H⁺] from pH', '[\\ce{H+}] = 10^{-\\text{pH}}'],
          ['pOH', '\\text{pOH} = -\\log[\\ce{OH-}]'],
          ['pH + pOH', '\\text{pH} + \\text{pOH} = 14'],
          ['Ka', 'K_a = \\frac{[\\ce{H+}][\\ce{A-}]}{[\\ce{HA}]}'],
          ['Kb', 'K_b = \\frac{[\\ce{BH+}][\\ce{OH-}]}{[\\ce{B}]}'],
          ['Ka × Kb = Kw', 'K_a \\times K_b = K_w'],
          ['Weak acid [H⁺]', '[\\ce{H+}] = \\sqrt{K_a \\cdot c}'],
          ['Henderson-Hasselbalch', '\\text{pH} = \\text{p}K_a + \\log\\frac{[\\ce{A-}]}{[\\ce{HA}]}'],
          ['pKa', '\\text{p}K_a = -\\log K_a'],
          ['pKb', '\\text{p}K_b = -\\log K_b'],
        ],
      },
      {
        name: '9. Redox',
        formulae: [
          ['Standard cell potential', 'E^\\circ_{\\text{cell}} = E^\\circ_{\\text{cathode}} - E^\\circ_{\\text{anode}}'],
          ['Charge', 'Q = It'],
          ['Moles of electrons', 'n(e^-) = \\frac{It}{F}'],
          ['Mass deposited', 'm = \\frac{ItM}{nF}'],
          ['Nernst equation', 'E = E^\\circ - \\frac{RT}{nF}\\ln Q'],
          ['Nernst (298 K)', 'E = E^\\circ - \\frac{0.0592}{n}\\log Q'],
          ['Faraday constant', 'F = 96485\\,\\text{C mol}^{-1}'],
        ],
      },
      {
        name: '10. Organic Chemistry',
        formulae: [
          ['Degree of unsaturation', '\\text{IHD} = \\frac{2C + 2 + N - H - X}{2}'],
          ['Alkane general formula', '\\ce{C_nH_{2n+2}}'],
          ['Alkene general formula', '\\ce{C_nH_{2n}}'],
        ],
      },
      {
        name: 'Common Reactions',
        formulae: [
          ['Water synthesis', '\\ce{2H2 + O2 -> 2H2O}'],
          ['Combustion of methane', '\\ce{CH4 + 2O2 -> CO2 + 2H2O}'],
          ['Acid-base neutralisation', '\\ce{HCl + NaOH -> NaCl + H2O}'],
          ['Haber process', '\\ce{N2 + 3H2 <=> 2NH3}'],
          ['Redox half-reaction', '\\ce{Cu^2+ + 2e- -> Cu}'],
        ],
      },
      {
        name: '11. Measurement',
        formulae: [
          ['Percentage error', '\\%\\text{ error} = \\frac{|\\text{exp} - \\text{accepted}|}{\\text{accepted}} \\times 100'],
          ['Beer-Lambert law', 'A = \\varepsilon lc'],
          ['Absorbance', 'A = -\\log T'],
          ['Rf value', 'R_f = \\frac{\\text{distance of substance}}{\\text{distance of solvent front}}'],
        ],
      },
    ],
  },
  {
    subject: 'IB Mathematics',
    categories: [
      {
        name: '1. Number & Algebra',
        formulae: [
          ['Arithmetic nth term', 'u_n = u_1 + (n-1)d'],
          ['Arithmetic series sum', 'S_n = \\frac{n}{2}(2u_1 + (n-1)d)'],
          ['Geometric nth term', 'u_n = u_1 r^{n-1}'],
          ['Geometric series sum', 'S_n = \\frac{u_1(1 - r^n)}{1 - r}'],
          ['Infinite geometric sum', 'S_\\infty = \\frac{u_1}{1-r}, \\quad |r|<1'],
          ['Compound interest', 'FV = PV\\left(1 + \\frac{r}{100k}\\right)^{kn}'],
          ['Log of a product', '\\log_a(xy) = \\log_a x + \\log_a y'],
          ['Log of a quotient', '\\log_a\\frac{x}{y} = \\log_a x - \\log_a y'],
          ['Log of a power', '\\log_a x^n = n\\log_a x'],
          ['Change of base', '\\log_a x = \\frac{\\ln x}{\\ln a}'],
          ['Binomial theorem', '(a+b)^n = \\sum_{r=0}^{n}\\binom{n}{r}a^{n-r}b^r'],
          ['Binomial coefficient', '\\binom{n}{r} = \\frac{n!}{r!(n-r)!}'],
          ['Permutations', 'P(n,r) = \\frac{n!}{(n-r)!}'],
          ['Complex modulus', '|z| = \\sqrt{a^2+b^2}'],
          ["De Moivre's theorem", '(r\\,\\text{cis}\\,\\theta)^n = r^n\\,\\text{cis}(n\\theta)'],
          ['Exponent law (multiply)', 'a^m \\times a^n = a^{m+n}'],
          ['Exponent law (power)', '(a^m)^n = a^{mn}'],
          ['Euler form', 'e^{i\\theta} = \\cos\\theta + i\\sin\\theta'],
          ['Roots of unity', 'z_k = r^{1/n}\\,\\text{cis}\\left(\\frac{\\theta + 2k\\pi}{n}\\right)'],
        ],
      },
      {
        name: '2. Functions',
        formulae: [
          ['Linear function', 'f(x) = mx + c'],
          ['Gradient', 'm = \\frac{y_2 - y_1}{x_2 - x_1}'],
          ['Quadratic formula', 'x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}'],
          ['Discriminant', '\\Delta = b^2 - 4ac'],
          ['Axis of symmetry', 'x = -\\frac{b}{2a}'],
          ['Vertex form', 'f(x) = a(x-h)^2 + k'],
          ['Exponential function', 'f(x) = ka^x + c'],
          ['Logistic function', 'f(x) = \\frac{L}{1 + Ce^{-kx}}'],
        ],
      },
      {
        name: '3. Geometry & Trigonometry',
        formulae: [
          ['Distance (2D)', 'd = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}'],
          ['Midpoint', 'M = \\left(\\frac{x_1+x_2}{2}, \\frac{y_1+y_2}{2}\\right)'],
          ['Cosine rule', 'c^2 = a^2 + b^2 - 2ab\\cos C'],
          ['Sine rule', '\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}'],
          ['Area of triangle', 'A = \\frac{1}{2}ab\\sin C'],
          ['Area of circle', 'A = \\pi r^2'],
          ['Volume of sphere', 'V = \\frac{4}{3}\\pi r^3'],
          ['Surface area of sphere', 'A = 4\\pi r^2'],
          ['Volume of cone', 'V = \\frac{1}{3}\\pi r^2 h'],
          ['Volume of cylinder', 'V = \\pi r^2 h'],
          ['Arc length', 'l = r\\theta'],
          ['Sector area', 'A = \\frac{1}{2}r^2\\theta'],
          ['Pythagorean identity', '\\sin^2\\theta + \\cos^2\\theta = 1'],
          ['Double angle (sin)', '\\sin 2\\theta = 2\\sin\\theta\\cos\\theta'],
          ['Double angle (cos)', '\\cos 2\\theta = \\cos^2\\theta - \\sin^2\\theta'],
          ['Compound angle (sin)', '\\sin(A \\pm B) = \\sin A\\cos B \\pm \\cos A\\sin B'],
          ['Compound angle (cos)', '\\cos(A \\pm B) = \\cos A\\cos B \\mp \\sin A\\sin B'],
          ['Dot product', '\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}|\\cos\\theta'],
          ['Cross product magnitude', '|\\vec{a} \\times \\vec{b}| = |\\vec{a}||\\vec{b}|\\sin\\theta'],
          ['Vector line equation', '\\vec{r} = \\vec{a} + t\\vec{b}'],
          ['Plane equation', '\\vec{r} \\cdot \\vec{n} = \\vec{a} \\cdot \\vec{n}'],
          ['Distance (3D)', 'd = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2 + (z_2-z_1)^2}'],
          ['Dot product (components)', '\\vec{a} \\cdot \\vec{b} = a_1b_1 + a_2b_2 + a_3b_3'],
          ['Angle between lines', '\\cos\\theta = \\frac{|\\vec{b}_1 \\cdot \\vec{b}_2|}{|\\vec{b}_1||\\vec{b}_2|}'],
          ['Angle between line and plane', '\\sin\\theta = \\frac{|\\vec{b} \\cdot \\vec{n}|}{|\\vec{b}||\\vec{n}|}'],
          ['Distance point to plane', 'd = \\frac{|ax_0+by_0+cz_0+d|}{\\sqrt{a^2+b^2+c^2}}'],
          ['Volume of pyramid', 'V = \\frac{1}{3}Ah'],
          ['tan identity', '\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}'],
          ['sec\u00b2 identity', '1 + \\tan^2\\theta = \\sec^2\\theta'],
        ],
      },
      {
        name: '4. Statistics & Probability',
        formulae: [
          ['Mean', '\\bar{x} = \\frac{\\sum x_i}{n}'],
          ['Variance', '\\sigma^2 = \\frac{\\sum(x_i - \\mu)^2}{n}'],
          ['Standard deviation', '\\sigma = \\sqrt{\\frac{\\sum(x_i - \\mu)^2}{n}}'],
          ['Sample std dev', 's_{n-1} = \\sqrt{\\frac{\\sum(x_i - \\bar{x})^2}{n-1}}'],
          ['Probability (complement)', 'P(A\') = 1 - P(A)'],
          ['Union', 'P(A \\cup B) = P(A) + P(B) - P(A \\cap B)'],
          ['Conditional probability', 'P(A|B) = \\frac{P(A \\cap B)}{P(B)}'],
          ["Bayes' theorem", 'P(A|B) = \\frac{P(B|A)P(A)}{P(B)}'],
          ['Expected value', 'E(X) = \\sum x_i P(X=x_i)'],
          ['Binomial probability', 'P(X=x) = \\binom{n}{x}p^x(1-p)^{n-x}'],
          ['Binomial mean', 'E(X) = np'],
          ['Binomial variance', '\\text{Var}(X) = np(1-p)'],
          ['Poisson probability', 'P(X=x) = \\frac{e^{-\\lambda}\\lambda^x}{x!}'],
          ['Normal standardisation', 'z = \\frac{x - \\mu}{\\sigma}'],
          ['Regression line', '\\hat{y} = ax + b'],
          ['Pearson r', 'r = \\frac{S_{xy}}{\\sqrt{S_{xx}S_{yy}}}'],
          ["Spearman's rank", 'r_s = 1 - \\frac{6\\sum d_i^2}{n(n^2-1)}'],
          ['Chi-squared', '\\chi^2 = \\sum\\frac{(f_o - f_e)^2}{f_e}'],
          ['t-test (one sample)', 't = \\frac{\\bar{x} - \\mu}{s/\\sqrt{n}}'],
          ['Confidence interval', '\\bar{x} \\pm z \\cdot \\frac{\\sigma}{\\sqrt{n}}'],
          ['Geometric distribution', 'P(X=x) = p(1-p)^{x-1}'],
          ['Chi-squared df (GOF)', '\\nu = k - 1'],
          ['Chi-squared df (independence)', '\\nu = (r-1)(c-1)'],
          ['Pooled two-sample t-test', 't = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_2}}}'],
        ],
      },
      {
        name: '5. Calculus',
        formulae: [
          ['First principles', "f'(x) = \\lim_{h \\to 0}\\frac{f(x+h)-f(x)}{h}"],
          ['Power rule', '\\frac{d}{dx}(x^n) = nx^{n-1}'],
          ['Product rule', "(fg)' = f'g + fg'"],
          ['Quotient rule', "\\left(\\frac{f}{g}\\right)' = \\frac{f'g - fg'}{g^2}"],
          ['Chain rule', '\\frac{dy}{dx} = \\frac{dy}{du} \\cdot \\frac{du}{dx}'],
          ['d/dx sin x', '\\frac{d}{dx}(\\sin x) = \\cos x'],
          ['d/dx cos x', '\\frac{d}{dx}(\\cos x) = -\\sin x'],
          ['d/dx eˣ', '\\frac{d}{dx}(e^x) = e^x'],
          ['d/dx ln x', '\\frac{d}{dx}(\\ln x) = \\frac{1}{x}'],
          ['∫ xⁿ dx', '\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C'],
          ['∫ 1/x dx', '\\int\\frac{1}{x}\\,dx = \\ln|x| + C'],
          ['∫ eˣ dx', '\\int e^x\\,dx = e^x + C'],
          ['∫ sin x dx', '\\int\\sin x\\,dx = -\\cos x + C'],
          ['∫ cos x dx', '\\int\\cos x\\,dx = \\sin x + C'],
          ['Integration by parts', '\\int u\\,dv = uv - \\int v\\,du'],
          ['Fundamental theorem', '\\int_a^b f(x)\\,dx = F(b) - F(a)'],
          ['Area between curves', 'A = \\int_a^b|f(x)-g(x)|\\,dx'],
          ['Volume of revolution', 'V = \\pi\\int_a^b[f(x)]^2\\,dx'],
          ['Trapezoidal rule', '\\int_a^b f(x)\\,dx \\approx \\frac{h}{2}[f(a)+f(b)+2\\sum f(x_i)]'],
          ["Euler's method", 'y_{n+1} = y_n + h \\cdot f(x_n, y_n)'],
          ['Maclaurin series', 'f(x) = \\sum_{n=0}^{\\infty}\\frac{f^{(n)}(0)}{n!}x^n'],
          ["L'Hôpital's rule", '\\lim_{x \\to a}\\frac{f(x)}{g(x)} = \\lim_{x \\to a}\\frac{f\'(x)}{g\'(x)}'],
          ['Velocity', 'v = \\frac{ds}{dt}'],
          ['Acceleration', 'a = \\frac{dv}{dt} = \\frac{d^2s}{dt^2}'],
          ['d/dx tan x', '\\frac{d}{dx}(\\tan x) = \\sec^2 x'],
          ['d/dx a\u02e3', '\\frac{d}{dx}(a^x) = a^x \\ln a'],
          ['d/dx arcsin x', '\\frac{d}{dx}(\\arcsin x) = \\frac{1}{\\sqrt{1-x^2}}'],
          ['d/dx arctan x', '\\frac{d}{dx}(\\arctan x) = \\frac{1}{1+x^2}'],
          ['\u222b sec\u00b2 x dx', '\\int\\sec^2 x\\,dx = \\tan x + C'],
          ['Separable ODE', '\\frac{dy}{dx} = f(x)g(y) \\Rightarrow \\int\\frac{dy}{g(y)} = \\int f(x)\\,dx'],
          ['Integrating factor', '\\frac{dy}{dx} + P(x)y = Q(x),\\quad \\mu = e^{\\int P\\,dx}'],
          ['2nd order ODE', 'a\\frac{d^2y}{dx^2}+b\\frac{dy}{dx}+cy=0'],
          ['Maclaurin: e\u02e3', 'e^x = 1 + x + \\frac{x^2}{2!} + \\frac{x^3}{3!} + \\cdots'],
          ['Maclaurin: sin x', '\\sin x = x - \\frac{x^3}{3!} + \\frac{x^5}{5!} - \\cdots'],
          ['Maclaurin: cos x', '\\cos x = 1 - \\frac{x^2}{2!} + \\frac{x^4}{4!} - \\cdots'],
          ['Maclaurin: ln(1+x)', '\\ln(1+x) = x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\cdots'],
        ],
      },
    ],
  },
  {
    subject: 'Economics',
    categories: [
      {
        name: 'Micro & Macro',
        formulae: [
          ['Price elasticity (PED)', 'PED = \\frac{\\%\\Delta Q_d}{\\%\\Delta P}'],
          ['Income elasticity (YED)', 'YED = \\frac{\\%\\Delta Q_d}{\\%\\Delta Y}'],
          ['Cross elasticity (XED)', 'XED = \\frac{\\%\\Delta Q_{dA}}{\\%\\Delta P_B}'],
          ['Multiplier', 'k = \\frac{1}{1 - MPC}'],
          ['GDP', 'GDP = C + I + G + (X - M)'],
          ['CPI inflation', '\\text{Inflation} = \\frac{CPI_t - CPI_{t-1}}{CPI_{t-1}} \\times 100'],
          ['Terms of trade', 'ToT = \\frac{\\text{Export price index}}{\\text{Import price index}} \\times 100'],
          ['PES', 'PES = \\frac{\\%\\Delta Q_s}{\\%\\Delta P}'],
          ['Total revenue', 'TR = P \\times Q'],
          ['Marginal cost', 'MC = \\frac{\\Delta TC}{\\Delta Q}'],
          ['Average cost', 'AC = \\frac{TC}{Q}'],
          ['Profit', '\\pi = TR - TC'],
          ['Unemployment rate', 'u = \\frac{\\text{unemployed}}{\\text{labour force}} \\times 100'],
          ['Real GDP', '\\text{Real GDP} = \\frac{\\text{Nominal GDP}}{\\text{GDP deflator}} \\times 100'],
          ['MPS', 'MPS = 1 - MPC'],
          ['Gini coefficient', 'G = \\frac{A}{A+B}'],
        ],
      },
    ],
  },
  {
    subject: 'IB Biology',
    categories: [
      {
        name: 'Statistics & Ecology',
        formulae: [
          ['Chi-squared test', '\\chi^2 = \\sum\\frac{(O-E)^2}{E}'],
          ['Simpson diversity index', 'D = \\frac{N(N-1)}{\\sum n_i(n_i-1)}'],
          ['Lincoln index', 'N = \\frac{n_1 \\times n_2}{n_{\\text{recaptured}}}'],
          ['Standard deviation', 's = \\sqrt{\\frac{\\sum(x_i - \\bar{x})^2}{n-1}}'],
          ['t-test', 't = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\frac{s_1^2}{n_1}+\\frac{s_2^2}{n_2}}}'],
        ],
      },
      {
        name: 'Genetics',
        formulae: [
          ['Hardy-Weinberg (alleles)', 'p + q = 1'],
          ['Hardy-Weinberg (genotypes)', 'p^2 + 2pq + q^2 = 1'],
          ['Magnification', 'M = \\frac{\\text{image size}}{\\text{actual size}}'],
        ],
      },
      {
        name: 'Ecology',
        formulae: [
          ['Net primary productivity', 'NPP = GPP - R'],
          ['Energy transfer', '\\% = \\frac{\\text{energy}_{n+1}}{\\text{energy}_n} \\times 100'],
        ],
      },
    ],
  },
  {
    subject: 'IB Computer Science',
    categories: [
      {
        name: 'Boolean Algebra',
        formulae: [
          ['AND gate', 'A \\cdot B'],
          ['OR gate', 'A + B'],
          ['NOT gate', '\\overline{A}'],
          ['NAND gate', '\\overline{A \\cdot B}'],
          ['XOR gate', 'A \\oplus B'],
          ["De Morgan's (AND)", '\\overline{A \\cdot B} = \\overline{A} + \\overline{B}'],
          ["De Morgan's (OR)", '\\overline{A + B} = \\overline{A} \\cdot \\overline{B}'],
        ],
      },
      {
        name: 'Complexity',
        formulae: [
          ['Constant', 'O(1)'],
          ['Logarithmic', 'O(\\log n)'],
          ['Linear', 'O(n)'],
          ['Linearithmic', 'O(n \\log n)'],
          ['Quadratic', 'O(n^2)'],
          ['Exponential', 'O(2^n)'],
        ],
      },
    ],
  },
];
